In [2]:
#Numpy Practice
import numpy as np

#Creating arrays using numpy
#Creating 1-D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
arr2 = np.array([1,2,3,4])
arr2.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [10]:
arr3 = np.array([[1,2,3,4],[5,6,7,8]])
arr3.shape

(2, 4)

In [15]:
arr4 = np.arange(1,10,2).reshape(5,1)
print(arr4)

[[1]
 [3]
 [5]
 [7]
 [9]]


In [17]:
#In-built numpy functions
#1. np.ones
arr5 = np.ones((2,2))
print(arr5)

#2. Identity array
arr6 = np.eye(3) # Square matrix with diagonals as 1 rest 0 arg is n in n*n 
print(arr6)

[[1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
#Attributes of numpy

arr = np.array([[1,2,3,4],[5,6,7,8]])

print("Array:\n", arr)
print("Shape:\n", arr.shape)
print("Number of dimensions:\n", arr.ndim)
print("Data Type:\n", arr.dtype)
print("Item Size:\n", arr.itemsize)

Array:
 [[1 2 3 4]
 [5 6 7 8]]
Shape:
 (2, 4)
Number of dimensions:
 2
Data Type:
 int32
Item Size:
 4


In [25]:
#Numpy Vectorized operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#Element wise operations
print(f"Element wise addition: {arr1+arr2}")
print(f"Element wise subtraction: {arr1-arr2}")
print(f"Element wise multiplication: {arr1*arr2}")
print(f"Element wise division: {arr1/arr2}")

Element wise addition: [11 22 33 44 55]
Element wise subtraction: [ -9 -18 -27 -36 -45]
Element wise multiplication: [ 10  40  90 160 250]
Element wise division: [0.1 0.1 0.1 0.1 0.1]


In [29]:
#Universal functions
arr = np.array([1,4,9,36])
print(np.sqrt(arr))

#Exponential
print(np.exp(arr))

[1. 2. 3. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 4.31123155e+15]


In [39]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr[1][2])
print(arr[2][3])
print(arr[0][0])
print(arr[1:])  #Slicing
print(arr[0:2, 2:4]) # To get 3 4 7 8
print(arr[1:3, 1:3]) # To get 6,7,10,11

7
12
1
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]


In [40]:
#Modify array elements
arr[0][0] = 1100
print(arr)

[[1100    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]


In [45]:
#Normalization
data = np.array([1,2,3,4,5])

mean  =np.mean(data)
print(mean)

std = np.std(data)
print(std)

normalized_data = (data-mean)/std
print(normalized_data)

3.0
1.4142135623730951
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [47]:
#Calculating mean,median,std dev and variance 
data = np.array([10,20,30,40,50])

print(f"Mean: {np.mean(data)}")
print(f"Median: {np.median(data)}")
print(f"Standard Deviation: {np.std(data)}")
print(f"Variance: {np.var(data)}")

Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
Variance: 200.0


In [55]:
#Logical Operation

data = np.array([1,2,3,4,5,6,7,8,9,10])

print(data[(data>3) & (data<9)])

[4 5 6 7 8]
